FROM node:18-bullseye-slim

ARG NODE_ENV=development
ENV NODE_ENV $NODE_ENV

EXPOSE 3000
EXPOSE 9229

COPY package.json yarn.lock ./
RUN yarn install
ENV PATH /app/node_modules/.bin:$PATH


WORKDIR /app

CMD ["npm", "run", "docker-start"]